#!/bin/bash

# Setup Tests for Dock Tile
# This script provides instructions for adding test targets to the Xcode project

set -e

echo "========================================"
echo "Dock Tile Test Setup Instructions"
echo "========================================"
echo ""
echo "The test files have been created in:"
echo "  - DockTileTests/ (Unit, Integration, Snapshot tests)"
echo "  - DockTileUITests/ (UI tests)"
echo ""
echo "To complete the setup, follow these steps in Xcode:"
echo ""
echo "1. OPEN THE PROJECT IN XCODE"
echo "   Open DockTile.xcodeproj"
echo ""
echo "2. ADD UNIT TEST TARGET"
echo "   - File > New > Target..."
echo "   - Select 'macOS' > 'Unit Testing Bundle'"
echo "   - Product Name: DockTileTests"
echo "   - Testing Framework: Swift Testing (or XCTest for compatibility)"
echo "   - Target to be Tested: DockTile"
echo "   - Click 'Finish'"
echo ""
echo "3. ADD UI TEST TARGET"
echo "   - File > New > Target..."
echo "   - Select 'macOS' > 'UI Testing Bundle'"
echo "   - Product Name: DockTileUITests"
echo "   - Target to be Tested: DockTile"
echo "   - Click 'Finish'"
echo ""
echo "4. MOVE TEST FILES INTO TARGETS"
echo "   - In Xcode's Project Navigator, drag the existing test files into"
echo "     their respective targets:"
echo ""
echo "   For DockTileTests target:"
echo "     - Unit/Managers/*.swift"
echo "     - Unit/Models/*.swift"
echo "     - Unit/Utilities/*.swift"
echo "     - Integration/*.swift"
echo "     - Mocks/*.swift"
echo ""
echo "   For DockTileUITests target:"
echo "     - ConfigurationFlowUITests.swift"
echo ""
echo "5. ADD SWIFT SNAPSHOT TESTING (Optional)"
echo "   - File > Add Package Dependencies..."
echo "   - Enter: https://github.com/pointfreeco/swift-snapshot-testing"
echo "   - Select version: Up to Next Major 1.17.0"
echo "   - Add to target: DockTileTests"
echo ""
echo "6. VERIFY SETUP"
echo "   - Product > Test (Cmd+U)"
echo "   - Tests should appear in the Test Navigator"
echo ""
echo "========================================"
echo "Test Files Summary"
echo "========================================"
echo ""

# Count test files
UNIT_TEST_COUNT=$(find /Users/karthik/Projects/dock-tile/DockTileTests/Unit -name "*.swift" 2>/dev/null | wc -l | tr -d ' ')
INTEGRATION_TEST_COUNT=$(find /Users/karthik/Projects/dock-tile/DockTileTests/Integration -name "*.swift" 2>/dev/null | wc -l | tr -d ' ')
MOCK_COUNT=$(find /Users/karthik/Projects/dock-tile/DockTileTests/Mocks -name "*.swift" 2>/dev/null | wc -l | tr -d ' ')
UI_TEST_COUNT=$(find /Users/karthik/Projects/dock-tile/DockTileUITests -name "*.swift" 2>/dev/null | wc -l | tr -d ' ')

echo "Unit Tests:        $UNIT_TEST_COUNT files"
echo "Integration Tests: $INTEGRATION_TEST_COUNT files"
echo "Mock Files:        $MOCK_COUNT files"
echo "UI Tests:          $UI_TEST_COUNT files"
echo ""
echo "Total:             $((UNIT_TEST_COUNT + INTEGRATION_TEST_COUNT + MOCK_COUNT + UI_TEST_COUNT)) files"
echo ""
echo "========================================"
echo "Run Tests Command (after setup)"
echo "========================================"
echo ""
echo "# Run all unit tests"
echo "xcodebuild test -project DockTile.xcodeproj -scheme DockTile \\"
echo "  -destination 'platform=macOS' -only-testing:DockTileTests"
echo ""
echo "# Run with coverage"
echo "xcodebuild test -project DockTile.xcodeproj -scheme DockTile \\"
echo "  -destination 'platform=macOS' -enableCodeCoverage YES"
echo ""
